import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-surface-variant": "#4d4635",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        outline: "#7f7663",
        "outline-variant": "#d0c5af",
        "surface-tint": "#735c00",
        primary: "#735c00",
        "on-primary": "#ffffff",
        "primary-container": "#d4af37",
        "on-primary-container": "#554300",
        "inverse-primary": "#e9c349",
        secondary: "#5e5e5b",
        "on-secondary": "#ffffff",
        "secondary-container": "#e1dfdb",
        "on-secondary-container": "#63635f",
        tertiary: "#5f5e58",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b5b3ac",
        "on-tertiary-container": "#464540",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffe088",
        "primary-fixed-dim": "#e9c349",
        "on-primary-fixed": "#241a00",
        "on-primary-fixed-variant": "#574500",
        "secondary-fixed": "#e4e2dd",
        "secondary-fixed-dim": "#c8c6c2",
        "on-secondary-fixed": "#1b1c19",
        "on-secondary-fixed-variant": "#474744",
        "tertiary-fixed": "#e5e2da",
        "tertiary-fixed-dim": "#c9c6bf",
        "on-tertiary-fixed": "#1c1c17",
        "on-tertiary-fixed-variant": "#474741",
        background: "#fcf9f8",
        "on-background": "#1c1b1b",
        "surface-variant": "#e5e2e1",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["var(--font-geist)", "Geist", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6" }],
        "body-md": ["16px", { lineHeight: "1.6" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "1.4" }],
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "section-gap": "120px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      boxShadow: {
        soft: "0 1px 2px rgba(28, 27, 27, 0.04), 0 8px 24px -12px rgba(115, 92, 0, 0.06)",
        ambient:
          "0 24px 48px -12px rgba(115, 92, 0, 0.10), 0 8px 20px -8px rgba(212, 175, 55, 0.12)",
        gold: "0 8px 24px -4px rgba(115, 92, 0, 0.18)",
      },
    },
  },
  plugins: [],
};

export default config;
