#!/usr/bin/env bash
# Encodes rendered CPU frames (render.mjs output) into the scroll videos.
#
#   scripts/render-cpu/encode.sh <desktop-png-dir> <mobile-png-dir>
#
# Frames are rendered at 2x and downscaled here, which is where the clean
# anti-aliasing comes from. Output, in public/sequence/:
#
#   cpu-desktop-<hash>.mp4   1280x720
#   cpu-mobile-<hash>.mp4     720x1280
#   poster-<hash>.webp       first desktop frame, small (still fallback)
#
# /sequence is served with a one-year immutable cache, so every file carries
# a content hash in its name and the paths are written to
# src/components/background/sequence-files.ts for the component to import.
#
# Encoding: H.264 with a keyframe every 3 frames and no B-frames, so a seek to
# any point decodes at most 3 frames — that is what makes scrubbing the
# playhead with the scroll instant.
set -euo pipefail

DESKTOP="${1:?desktop frame dir}"
MOBILE="${2:?mobile frame dir}"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/public/sequence"
MODULE="$ROOT/src/components/background/sequence-files.ts"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

encode() { # <png-dir> <scale> <crf> <out>
  ffmpeg -v error -y -framerate 30 -i "$1/%04d.png" \
    -vf "scale=$2:flags=lanczos" \
    -c:v libx264 -preset slow -crf "$3" -g 3 -bf 0 -pix_fmt yuv420p \
    -movflags +faststart -an "$4"
}
encode "$DESKTOP" 1280:720 26 "$TMP/cpu-desktop.mp4"
encode "$MOBILE" 720:1280 27 "$TMP/cpu-mobile.mp4"
ffmpeg -v error -y -i "$DESKTOP/0000.png" -frames:v 1 \
  -vf "scale=960:540:flags=lanczos" -c:v libwebp -quality 55 "$TMP/poster.webp"

# Replace everything in public/sequence (files only — on Windows a folder
# another process has open can't be removed).
mkdir -p "$OUT"
find "$OUT" -mindepth 1 -type f -delete
find "$OUT" -mindepth 1 -type d -empty -delete 2>/dev/null || true

hashed() { # <file> <stem> <ext> → prints the published name
  local h
  h="$(sha256sum "$1" | cut -c1-10)"
  cp "$1" "$OUT/$2-$h.$3"
  echo "$2-$h.$3"
}
D="$(hashed "$TMP/cpu-desktop.mp4" cpu-desktop mp4)"
M="$(hashed "$TMP/cpu-mobile.mp4" cpu-mobile mp4)"
P="$(hashed "$TMP/poster.webp" poster webp)"

cat > "$MODULE" <<TS
// Generated by scripts/render-cpu/encode.sh — do not edit by hand.
// File names carry a content hash because /sequence is cached immutably.
export const SEQUENCE_FILES = {
  desktop: "/sequence/$D",
  mobile: "/sequence/$M",
  poster: "/sequence/$P",
} as const;
TS

echo "desktop: $D ($(du -h "$OUT/$D" | cut -f1))"
echo "mobile:  $M ($(du -h "$OUT/$M" | cut -f1))"
echo "poster:  $P ($(du -h "$OUT/$P" | cut -f1))"
