// Generated by scripts/render-cpu/encode.sh — do not edit by hand.
// File names carry a content hash because /sequence is cached immutably.
export const SEQUENCE_FILES = {
  desktop: "/sequence/cpu-desktop-89931273fc.mp4",
  mobile: "/sequence/cpu-mobile-f7119fa937.mp4",
  poster: "/sequence/poster-8dae31cf69.webp",
} as const;
